Algoritmo "contadorPara1a10"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/8/2023
Var
// Seção de Declarações das variáveis 
      c,limite:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreval("limite")
       leia (limite)
       para c <- limite ate 1 passo -1 faca
       Escreval (c)
       fimpara

Fimalgoritmo