algoritmo "aula 4 triangulos"
// Função :
// Autor :   DD
// Data : 06/08/2023


var
// Seção de Declarações
l1, l2, l3: Real
eq, es: logico

inicio
// Seção de Comandos
Escreva ("Digite o primeiro lado: ")
leia(l1)
 Escreva ("Digite o segundo lado: ")
leia(l2)
 Escreva ("Digite o terceiro lado: ")
leia(l3)
eq <- (l1=12) e (l2 = l3) e (l1 = l3)
es <- (l1<>L2) e (l2 <> l3) e (l1 <> l3)
Escreval("o triangulo é equilatero? ", eq)
Escreval (" o triangulo é equilatero?", es)
fimalgoritmo
