Algoritmo "Primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcos Daniel
// Data atual  : 04/08/2023




Var
// Seção de Declarações das variáveis 
msg : caractere



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
msg <- "Olá, Mundo!"
escreval (msg)




Fimalgoritmo