Algoritmo "Fibonacci"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/8/2023
Var
   // Seção de Declarações das variáveis
   c, t1, t2, t3:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   t1 <- 0
   escreva (t1)
   t2 <- 1
   escreva (t2)
   
   para c := 3 ate 15 faca
   t3 := t1 + t2
   escreva (t3)
   t1 := t2
   t2 := t3
   fimpara
   

Fimalgoritmo