Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/8/2023
Var
   // Seção de Declarações das variáveis
   cont, v: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva ("Digite um valor: ")
   leia v
   para cont < 0 ate v passo 2 faca
   escreval (cont)
   fimpara

Fimalgoritmo