algoritmo "Creuza parcelas"
//  
//  
// Função :
// Autor :
// Data : 12/08/2023
// Seção de Declarações 
var
    numeroParcelas, total, valorEmprestimo: real
inicio
// Seção de Comandos
escreva ("Qual o valor do emprestimo? ")
leia (valorEmprestimo)
Escreva ("Em quanta parcelas deseja dividir?" )
Leia (numeroParcelas)
total <- valorEmprestimo / numeroParcelas
Escreval ("vou pagar ", NumeroParcelas)
Escreval ("parcelas de R$", total:2:2)
 
fimalgoritmo
