Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aula 3 – Comando de Entrada e Operadores (função)
// Autor(a)    : dani
// Data atual  : 04/08/2023
// Algoritimo "MeuNome"
Var
// Seção de Declarações das variáveis 
Nome: Caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


escreva ("Digite seu nome: ")
leia (Nome)
Escreva ("Muito prazer ", Nome)


Fimalgoritmo